"""Protocol for hospital discharge studies summary.

This module defines the protocols (interfaces) for discharge studies objects.
The Hospital Discharge Studies Summary Section records the results of observations
generated by laboratories, imaging procedures, and other procedures at discharge.

The section includes hematology, chemistry, serology, virology, toxicology,
microbiology, plain x-ray, ultrasound, CT, MRI, angiography, echocardiography,
nuclear medicine, pathology, and procedure observations.

Template ID: 2.16.840.1.113883.10.20.22.2.16
LOINC Code: 11493-4 (Hospital Discharge Studies Summary)
"""

from datetime import date, datetime
from typing import Optional, Protocol, Sequence


class DischargeStudyObservationProtocol(Protocol):
    """Protocol for a single discharge study observation.

    Defines the interface that discharge study observation objects must implement
    to be used with the Hospital Discharge Studies Summary section builder.

    This protocol is based on the Result Observation entry but is specifically
    intended for diagnostic studies performed during hospitalization and
    reported at discharge.

    Attributes:
        study_name: Name of the study/test (e.g., "Chest X-Ray", "CBC", "Echocardiogram")
        study_code: LOINC code for the study/test
        value: Measured value (numeric or text result)
        unit: Unit of measurement (e.g., "mg/dL", "mmHg"). Optional for coded/text values.
        status: Status of the result (e.g., "completed", "preliminary", "final")
        effective_time: Date and time the study was performed
        value_type: Type of value - "PQ" (physical quantity), "CD" (coded), or "ST" (string).
                   Defaults to "PQ" if unit is provided, otherwise "ST".
        interpretation: Optional interpretation code (e.g., "N" for normal, "A" for abnormal)
        reference_range_low: Optional lower bound of reference range
        reference_range_high: Optional upper bound of reference range
        reference_range_unit: Optional unit for reference range (should match value unit)
    """

    study_name: str
    study_code: str
    value: str
    unit: Optional[str]
    status: str
    effective_time: date | datetime
    value_type: Optional[str]
    interpretation: Optional[str]
    reference_range_low: Optional[str]
    reference_range_high: Optional[str]
    reference_range_unit: Optional[str]


class DischargeStudyOrganizerProtocol(Protocol):
    """Protocol for a group of related discharge studies (e.g., a study panel).

    Defines the interface for a discharge study organizer that groups related
    test results or imaging studies performed during hospitalization.

    Attributes:
        study_panel_name: Name of the panel (e.g., "Complete Blood Count",
                         "Cardiac Imaging Panel", "Metabolic Panel")
        study_panel_code: LOINC code for the panel
        status: Status of the organizer (e.g., "completed", "active")
        effective_time: Date and time when the panel was collected/performed
        studies: Sequence of study observations in this panel
    """

    study_panel_name: str
    study_panel_code: str
    status: str
    effective_time: date | datetime
    studies: Sequence[DischargeStudyObservationProtocol]
